name: Pages

on:
 workflow_dispatch:
 push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Change workdir
        run: cd Genshin-Impact-Wish-Simulator
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.OS }}-npm-frontend-cache
          restore-keys: |
            ${{ runner.OS }}-npm-frontend-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Package
        run: 7z a -tzip frontend.zip ./.vercel/output/static
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend.zip
