name: Release

on:
 workflow_dispatch:
 push:
   tags:
     - "v*"
jobs:
  app:
    name: Build app
    uses: ./.github/workflows/app.yml
  page:
    name: Build&Update pages
    uses: ./.github/workflows/page.yml
  release:
    needs: app
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
            files: ./**/genish-impact*.*