name: Deploy docs

on:
 workflow_dispatch:
 workflow_call:
 pull_request:
    branches:
      - main # default branch
    paths:
      - webdocs/**/**
 push:
    branches:
      - main # default branch
    paths:
      - webdocs/**/**

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ./webdocs/node_modules
          key: ${{ runner.OS }}-npm-frontend-cache
          restore-keys: |
            ${{ runner.OS }}-npm-frontend-cache
      - name: Install Dependencies
        run: |
         cd webdocs
         yarn install
      - name: Build
        run: |
         cd webdocs
         yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webdocs/docs/.vitepress/dist
